import type { Brand, Category, Product } from "./types";

/**
 * Bundled sample catalogue.
 *
 * This is the fallback data source used whenever Supabase is not configured
 * (or its tables are empty), so the storefront always renders a full,
 * good-looking catalogue during the demo phase. The exact same shape is
 * returned by the Supabase queries in `data.ts`.
 *
 * NOTE (demo behaviour): every product has `stock_quantity: 0` while
 * `in_stock: true`. Products therefore appear buyable and can be added to the
 * cart, but the server-side stock validation at checkout finds zero available
 * units and reports them as out of stock — exactly the requested flow.
 *
 * Images are real photography from Unsplash (URLs verified to resolve).
 */

// Build a sized Unsplash URL from a verified photo id.
const u = (id: string, w = 1400) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const sampleCategories: Category[] = [
  {
    id: "cat-skincare",
    name: "Skincare",
    slug: "skincare",
    description: "Serums, moisturisers and cleansers for radiant, healthy skin.",
    image_url: u("1556228720-195a672e8a03", 900),
    sort_order: 1,
  },
  {
    id: "cat-makeup",
    name: "Makeup",
    slug: "makeup",
    description: "Complexion, lips and eyes — from everyday to statement looks.",
    image_url: u("1522335789203-aabd1fc54bc9", 900),
    sort_order: 2,
  },
  {
    id: "cat-fragrance",
    name: "Fragrance",
    slug: "fragrance",
    description: "Eau de parfum, oud and body mists to define your signature.",
    image_url: u("1541643600914-78b084683601", 900),
    sort_order: 3,
  },
  {
    id: "cat-hair",
    name: "Hair",
    slug: "hair",
    description: "Repair, nourish and style with salon-grade haircare.",
    image_url: u("1583209814683-c023dd293cc6", 900),
    sort_order: 4,
  },
  {
    id: "cat-bath-body",
    name: "Bath & Body",
    slug: "bath-body",
    description: "Lotions, scrubs and hand care for head-to-toe softness.",
    image_url: u("1526947425960-945c6e72858f", 900),
    sort_order: 5,
  },
  {
    id: "cat-tools",
    name: "Tools & Accessories",
    slug: "tools",
    description: "Brushes, rollers and beauty tools for a flawless finish.",
    image_url: u("1547887538-e3a2f32cb1cc", 900),
    sort_order: 6,
  },
];

export const sampleBrands: Brand[] = [
  { id: "brand-aurelie", name: "Aurélie Paris", slug: "aurelie-paris", logo_url: null },
  { id: "brand-noor", name: "Noor & Co", slug: "noor-co", logo_url: null },
  { id: "brand-velvet", name: "Velvet Atelier", slug: "velvet-atelier", logo_url: null },
  { id: "brand-maison", name: "Maison Lys", slug: "maison-lys", logo_url: null },
  { id: "brand-dune", name: "Dune & Rose", slug: "dune-rose", logo_url: null },
  { id: "brand-kosei", name: "Kōsei", slug: "kosei", logo_url: null },
];

type ProductSeed = Omit<Product, "currency" | "in_stock" | "stock_quantity" | "category_name" | "brand_name"> & {
  category_slug: string;
  brand_slug: string;
};

const seeds: ProductSeed[] = [
  // ---------- Skincare ----------
  {
    id: "prod-01",
    name: "Radiance Vitamin C Serum",
    slug: "radiance-vitamin-c-serum",
    short_description: "Brightening 15% vitamin C serum for an even, luminous glow.",
    description:
      "A lightweight daily serum powered by 15% stabilised vitamin C, vitamin E and ferulic acid. Visibly brightens, evens tone and defends against environmental stress for a lit-from-within radiance. Fragrance-free and suitable for all skin types.",
    price: 24.5,
    compare_at_price: 29.0,
    images: [u("1620916566398-39f1143ab7be"), u("1608248597279-f99d160bfcbc")],
    category_slug: "skincare",
    brand_slug: "aurelie-paris",
    rating: 4.8,
    review_count: 214,
    is_featured: true,
    is_new: false,
    tags: ["serum", "brightening", "vitamin-c", "vegan"],
  },
  {
    id: "prod-02",
    name: "Hydra-Plump Hyaluronic Serum",
    slug: "hydra-plump-hyaluronic-serum",
    short_description: "Multi-weight hyaluronic acid for deep, lasting hydration.",
    description:
      "Five molecular weights of hyaluronic acid quench skin at every layer, plumping fine lines and leaving a dewy, cushioned finish. Layer under moisturiser morning and night.",
    price: 22.0,
    compare_at_price: null,
    images: [u("1608248597279-f99d160bfcbc"), u("1620916566398-39f1143ab7be")],
    category_slug: "skincare",
    brand_slug: "noor-co",
    rating: 4.7,
    review_count: 168,
    is_featured: false,
    is_new: true,
    tags: ["serum", "hydration"],
  },
  {
    id: "prod-03",
    name: "Overnight Retinol Renewal Cream",
    slug: "overnight-retinol-renewal-cream",
    short_description: "Encapsulated retinol cream that smooths and refines overnight.",
    description:
      "Time-released encapsulated retinol works with peptides and squalane to resurface, soften lines and refine texture while you sleep — with less irritation than traditional retinol.",
    price: 28.0,
    compare_at_price: 34.0,
    images: [u("1611930022073-b7a4ba5fcccd"), u("1598440947619-2c35fc9aa908")],
    category_slug: "skincare",
    brand_slug: "velvet-atelier",
    rating: 4.6,
    review_count: 132,
    is_featured: true,
    is_new: false,
    tags: ["cream", "anti-aging", "retinol"],
  },
  {
    id: "prod-04",
    name: "Rose Dew Facial Toner",
    slug: "rose-dew-facial-toner",
    short_description: "Alcohol-free Damask rose toner that soothes and refreshes.",
    description:
      "Steam-distilled Damask rose water balances and hydrates while gentle PHAs sweep away dullness. A refreshing mist-on step for calm, glowing skin.",
    price: 12.5,
    compare_at_price: null,
    images: [u("1556228453-efd6c1ff04f6")],
    category_slug: "skincare",
    brand_slug: "maison-lys",
    rating: 4.5,
    review_count: 96,
    is_featured: false,
    is_new: false,
    tags: ["toner", "rose"],
  },
  {
    id: "prod-05",
    name: "Gentle Cream Cleanser",
    slug: "gentle-cream-cleanser",
    short_description: "Creamy non-stripping cleanser for soft, comfortable skin.",
    description:
      "A silky cream-to-milk cleanser that melts away makeup and impurities without stripping the skin barrier. Leaves skin clean, calm and never tight.",
    price: 10.0,
    compare_at_price: null,
    images: [u("1556228720-195a672e8a03")],
    category_slug: "skincare",
    brand_slug: "noor-co",
    rating: 4.4,
    review_count: 78,
    is_featured: false,
    is_new: false,
    tags: ["cleanser"],
  },
  {
    id: "prod-06",
    name: "Barrier Repair Moisturiser",
    slug: "barrier-repair-moisturiser",
    short_description: "Ceramide + niacinamide cream that rebuilds a resilient barrier.",
    description:
      "A rich yet fast-absorbing moisturiser with ceramides, niacinamide and shea to restore a compromised barrier, lock in moisture and reduce redness.",
    price: 19.5,
    compare_at_price: null,
    images: [u("1598440947619-2c35fc9aa908"), u("1611930022073-b7a4ba5fcccd")],
    category_slug: "skincare",
    brand_slug: "kosei",
    rating: 4.7,
    review_count: 143,
    is_featured: false,
    is_new: true,
    tags: ["moisturiser", "ceramide"],
  },

  // ---------- Makeup ----------
  {
    id: "prod-07",
    name: "Velvet Matte Lipstick — Rosewood",
    slug: "velvet-matte-lipstick-rosewood",
    short_description: "Full-coverage matte lipstick with a weightless, comfy feel.",
    description:
      "Richly pigmented rosewood matte that glides on creamy and sets to a soft-focus velvet finish. Infused with jojoba oil so lips stay comfortable, never dry.",
    price: 9.5,
    compare_at_price: null,
    images: [u("1512496015851-a90fb38ba796"), u("1596462502278-27bfdc403348")],
    category_slug: "makeup",
    brand_slug: "velvet-atelier",
    rating: 4.6,
    review_count: 201,
    is_featured: true,
    is_new: false,
    tags: ["lipstick", "matte"],
  },
  {
    id: "prod-08",
    name: "Luminous Silk Foundation",
    slug: "luminous-silk-foundation",
    short_description: "Medium-coverage foundation with a natural radiant finish.",
    description:
      "A breathable, buildable foundation that evens tone while letting skin look like skin. Hydrating hyaluronic complex keeps the finish fresh for up to 16 hours.",
    price: 21.0,
    compare_at_price: 25.0,
    images: [u("1596462502278-27bfdc403348")],
    category_slug: "makeup",
    brand_slug: "aurelie-paris",
    rating: 4.5,
    review_count: 176,
    is_featured: false,
    is_new: false,
    tags: ["foundation", "complexion"],
  },
  {
    id: "prod-09",
    name: "Sunset Eyeshadow Palette",
    slug: "sunset-eyeshadow-palette",
    short_description: "12 warm mattes and shimmers for day-to-night eyes.",
    description:
      "Twelve highly blendable warm-toned shades — silky mattes and foil shimmers — in a curated palette that takes you from soft daytime looks to bold evening drama.",
    price: 18.0,
    compare_at_price: null,
    images: [u("1522335789203-aabd1fc54bc9"), u("1596704017254-9b121068fb31")],
    category_slug: "makeup",
    brand_slug: "dune-rose",
    rating: 4.8,
    review_count: 254,
    is_featured: true,
    is_new: true,
    tags: ["eyeshadow", "palette"],
  },
  {
    id: "prod-10",
    name: "Featherlight Setting Powder",
    slug: "featherlight-setting-powder",
    short_description: "Finely milled powder that blurs and sets without cakiness.",
    description:
      "A translucent, finely milled powder that sets makeup, controls shine and softly blurs pores for an airbrushed finish that lasts all day.",
    price: 14.0,
    compare_at_price: null,
    images: [u("1596704017254-9b121068fb31")],
    category_slug: "makeup",
    brand_slug: "kosei",
    rating: 4.4,
    review_count: 88,
    is_featured: false,
    is_new: false,
    tags: ["powder", "setting"],
  },
  {
    id: "prod-11",
    name: "Lengthening Volume Mascara",
    slug: "lengthening-volume-mascara",
    short_description: "Buildable mascara for length, lift and clump-free volume.",
    description:
      "A tapered brush and flexible formula wrap every lash for dramatic length and volume that holds its curl all day and removes easily with warm water.",
    price: 11.0,
    compare_at_price: null,
    images: [u("1598662957563-ee4965d4d72c")],
    category_slug: "makeup",
    brand_slug: "noor-co",
    rating: 4.6,
    review_count: 190,
    is_featured: false,
    is_new: false,
    tags: ["mascara", "eyes"],
  },
  {
    id: "prod-12",
    name: "Dewy Glow Liquid Blush",
    slug: "dewy-glow-liquid-blush",
    short_description: "Sheer liquid blush for a natural, lit-from-within flush.",
    description:
      "A few dots melt into skin for a healthy, dewy flush of colour. Long-wearing and buildable, it works beautifully over makeup or bare skin.",
    price: 12.5,
    compare_at_price: null,
    images: [u("1616394584738-fc6e612e71b9")],
    category_slug: "makeup",
    brand_slug: "dune-rose",
    rating: 4.7,
    review_count: 121,
    is_featured: false,
    is_new: true,
    tags: ["blush", "cheeks"],
  },

  // ---------- Fragrance ----------
  {
    id: "prod-13",
    name: "Oud Royale Eau de Parfum",
    slug: "oud-royale-eau-de-parfum",
    short_description: "Opulent oud, rose and amber — a bold Arabian signature.",
    description:
      "A regal unisex oud built on smoky agarwood, Damask rose and warm amber with a whisper of saffron. Long-lasting sillage crafted for the Gulf's love of oud.",
    price: 52.0,
    compare_at_price: 60.0,
    images: [u("1541643600914-78b084683601"), u("1592945403244-b3fbafd7f539")],
    category_slug: "fragrance",
    brand_slug: "maison-lys",
    rating: 4.9,
    review_count: 312,
    is_featured: true,
    is_new: false,
    tags: ["perfume", "oud", "unisex"],
  },
  {
    id: "prod-14",
    name: "Jasmine Nuit Eau de Parfum",
    slug: "jasmine-nuit-eau-de-parfum",
    short_description: "Night-blooming jasmine, tuberose and creamy sandalwood.",
    description:
      "An intoxicating floral built around night-blooming jasmine and tuberose, grounded by creamy sandalwood and vanilla for an elegant, romantic trail.",
    price: 45.0,
    compare_at_price: null,
    images: [u("1592945403244-b3fbafd7f539"), u("1541643600914-78b084683601")],
    category_slug: "fragrance",
    brand_slug: "aurelie-paris",
    rating: 4.8,
    review_count: 205,
    is_featured: true,
    is_new: false,
    tags: ["perfume", "floral"],
  },
  {
    id: "prod-15",
    name: "Amber & Musk Eau de Toilette",
    slug: "amber-musk-eau-de-toilette",
    short_description: "Soft, skin-like amber and musk for everyday elegance.",
    description:
      "A cosy, versatile blend of golden amber, white musk and a hint of vanilla — clean and comforting, perfect for daily wear.",
    price: 34.0,
    compare_at_price: null,
    images: [u("1523293182086-7651a899d37f")],
    category_slug: "fragrance",
    brand_slug: "velvet-atelier",
    rating: 4.6,
    review_count: 140,
    is_featured: false,
    is_new: false,
    tags: ["perfume", "amber", "musk"],
  },
  {
    id: "prod-16",
    name: "Citrus Bloom Body Mist",
    slug: "citrus-bloom-body-mist",
    short_description: "Refreshing bergamot and peony mist for a light daily veil.",
    description:
      "A sparkling body mist of bergamot, peony and white tea for an instant refresh. Light enough to layer and reapply throughout the day.",
    price: 16.0,
    compare_at_price: null,
    images: [u("1571781926291-c477ebfd024b")],
    category_slug: "fragrance",
    brand_slug: "dune-rose",
    rating: 4.4,
    review_count: 74,
    is_featured: false,
    is_new: true,
    tags: ["mist", "fresh"],
  },

  // ---------- Hair ----------
  {
    id: "prod-17",
    name: "Argan Repair Hair Oil",
    slug: "argan-repair-hair-oil",
    short_description: "Weightless argan oil that smooths frizz and adds shine.",
    description:
      "A fast-absorbing blend of Moroccan argan and camellia oils tames frizz, seals split ends and leaves hair glossy — never greasy. Heat-protects to 220°C.",
    price: 17.0,
    compare_at_price: null,
    images: [u("1583209814683-c023dd293cc6"), u("1607602132700-068258431c6c")],
    category_slug: "hair",
    brand_slug: "kosei",
    rating: 4.7,
    review_count: 158,
    is_featured: true,
    is_new: false,
    tags: ["hair-oil", "repair"],
  },
  {
    id: "prod-18",
    name: "Silk Bond Repair Shampoo",
    slug: "silk-bond-repair-shampoo",
    short_description: "Bond-building shampoo that strengthens damaged hair.",
    description:
      "A sulphate-free shampoo with bond-building technology and silk proteins that gently cleanses while restoring strength to over-processed, brittle hair.",
    price: 13.5,
    compare_at_price: null,
    images: [u("1607602132700-068258431c6c")],
    category_slug: "hair",
    brand_slug: "noor-co",
    rating: 4.5,
    review_count: 92,
    is_featured: false,
    is_new: false,
    tags: ["shampoo"],
  },
  {
    id: "prod-19",
    name: "Hydrating Hair Mask",
    slug: "hydrating-hair-mask",
    short_description: "Deep-conditioning weekly mask for soft, manageable hair.",
    description:
      "An intensive weekly treatment with shea butter and hydrolysed keratin that deeply nourishes dry, damaged lengths for softer, more manageable hair in one use.",
    price: 15.0,
    compare_at_price: 18.0,
    images: [u("1606787366850-de6330128bfc")],
    category_slug: "hair",
    brand_slug: "velvet-atelier",
    rating: 4.6,
    review_count: 110,
    is_featured: false,
    is_new: false,
    tags: ["mask", "conditioning"],
  },

  // ---------- Bath & Body ----------
  {
    id: "prod-20",
    name: "Neroli Body Lotion",
    slug: "neroli-body-lotion",
    short_description: "Fast-absorbing neroli lotion for 24h softness.",
    description:
      "A lightweight, fast-absorbing lotion scented with neroli and orange blossom, enriched with shea and glycerin for all-day, non-greasy hydration.",
    price: 11.5,
    compare_at_price: null,
    images: [u("1526947425960-945c6e72858f")],
    category_slug: "bath-body",
    brand_slug: "maison-lys",
    rating: 4.5,
    review_count: 83,
    is_featured: false,
    is_new: false,
    tags: ["lotion", "body"],
  },
  {
    id: "prod-21",
    name: "Exfoliating Sugar Scrub",
    slug: "exfoliating-sugar-scrub",
    short_description: "Cane-sugar scrub that polishes skin silky-smooth.",
    description:
      "A melting sugar scrub with cane crystals and nourishing oils that buffs away dullness and leaves skin polished, soft and lightly scented.",
    price: 9.0,
    compare_at_price: null,
    images: [u("1631214540553-ff044a3ff1d4")],
    category_slug: "bath-body",
    brand_slug: "dune-rose",
    rating: 4.4,
    review_count: 67,
    is_featured: false,
    is_new: true,
    tags: ["scrub", "exfoliate"],
  },
  {
    id: "prod-22",
    name: "Shea Hand Cream Trio",
    slug: "shea-hand-cream-trio",
    short_description: "Three travel hand creams — the perfect little gift.",
    description:
      "A trio of richly nourishing shea hand creams in three signature scents. Beautifully boxed and travel-sized — an ideal gift or handbag essential.",
    price: 8.5,
    compare_at_price: 10.0,
    images: [u("1550928431-ee0ec6db30d3")],
    category_slug: "bath-body",
    brand_slug: "kosei",
    rating: 4.6,
    review_count: 129,
    is_featured: false,
    is_new: false,
    tags: ["hand-cream", "gift"],
  },

  // ---------- Tools & Accessories ----------
  {
    id: "prod-23",
    name: "Jade Facial Roller & Gua Sha Set",
    slug: "jade-facial-roller-gua-sha-set",
    short_description: "Cooling jade roller and gua sha for a de-puffing ritual.",
    description:
      "A genuine jade roller and gua sha stone that cool and sculpt — massage to de-puff, boost circulation and help serums absorb. Comes in a keepsake pouch.",
    price: 14.5,
    compare_at_price: null,
    images: [u("1547887538-e3a2f32cb1cc"), u("1631730359585-38a4935cbec4")],
    category_slug: "tools",
    brand_slug: "velvet-atelier",
    rating: 4.7,
    review_count: 175,
    is_featured: true,
    is_new: false,
    tags: ["tools", "gift", "ritual"],
  },
  {
    id: "prod-24",
    name: "Pro Blending Makeup Brush Set",
    slug: "pro-blending-makeup-brush-set",
    short_description: "10-piece vegan brush set for a flawless application.",
    description:
      "Ten ultra-soft vegan brushes for face and eyes, with a chic vegan-leather roll. Densely packed synthetic bristles blend product seamlessly for a pro finish.",
    price: 22.0,
    compare_at_price: 27.0,
    images: [u("1512207736890-6ffed8a84e8d")],
    category_slug: "tools",
    brand_slug: "aurelie-paris",
    rating: 4.5,
    review_count: 98,
    is_featured: false,
    is_new: true,
    tags: ["brushes", "tools", "vegan"],
  },
];

const categoryName = (slug: string) =>
  sampleCategories.find((c) => c.slug === slug)?.name ?? slug;
const brandName = (slug: string) => sampleBrands.find((b) => b.slug === slug)?.name ?? null;

export const sampleProducts: Product[] = seeds.map((s) => ({
  ...s,
  currency: "BHD",
  category_name: categoryName(s.category_slug),
  brand_name: brandName(s.brand_slug),
  // Demo phase: listed for sale, but zero real inventory → out of stock at checkout.
  in_stock: true,
  stock_quantity: 0,
}));
