-- ============================================================================
-- Seed data for the Arabic Souk beauty store
-- GENERATED from src/lib/sample-data.ts by scripts/gen-seed.ts — do not edit by hand.
-- Safe to re-run: every insert upserts on the unique slug.
-- ============================================================================

insert into public.categories (name, slug, description, image_url, sort_order) values
  ('Skincare', 'skincare', 'Serums, moisturisers and cleansers for radiant, healthy skin.', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80', 1),
  ('Makeup', 'makeup', 'Complexion, lips and eyes — from everyday to statement looks.', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80', 2),
  ('Fragrance', 'fragrance', 'Eau de parfum, oud and body mists to define your signature.', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80', 3),
  ('Hair', 'hair', 'Repair, nourish and style with salon-grade haircare.', 'https://images.unsplash.com/photo-1583209814683-c023dd293cc6?auto=format&fit=crop&w=900&q=80', 4),
  ('Bath & Body', 'bath-body', 'Lotions, scrubs and hand care for head-to-toe softness.', 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=900&q=80', 5),
  ('Tools & Accessories', 'tools', 'Brushes, rollers and beauty tools for a flawless finish.', 'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=900&q=80', 6)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description,
  image_url = excluded.image_url, sort_order = excluded.sort_order;

insert into public.brands (name, slug, logo_url) values
  ('Aurélie Paris', 'aurelie-paris', null),
  ('Noor & Co', 'noor-co', null),
  ('Velvet Atelier', 'velvet-atelier', null),
  ('Maison Lys', 'maison-lys', null),
  ('Dune & Rose', 'dune-rose', null),
  ('Kōsei', 'kosei', null)
on conflict (slug) do update set name = excluded.name, logo_url = excluded.logo_url;

insert into public.products
  (name, slug, description, short_description, price, compare_at_price, currency,
   images, category_id, brand_id, rating, review_count, stock_quantity, in_stock,
   is_featured, is_new, tags)
values
  ('Radiance Vitamin C Serum', 'radiance-vitamin-c-serum', 'A lightweight daily serum powered by 15% stabilised vitamin C, vitamin E and ferulic acid. Visibly brightens, evens tone and defends against environmental stress for a lit-from-within radiance. Fragrance-free and suitable for all skin types.', 'Brightening 15% vitamin C serum for an even, luminous glow.', 24.5, 29, 'BHD', '["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'aurelie-paris'), 4.8, 214, 0, true, true, false, '{"serum","brightening","vitamin-c","vegan"}'),
  ('Hydra-Plump Hyaluronic Serum', 'hydra-plump-hyaluronic-serum', 'Five molecular weights of hyaluronic acid quench skin at every layer, plumping fine lines and leaving a dewy, cushioned finish. Layer under moisturiser morning and night.', 'Multi-weight hyaluronic acid for deep, lasting hydration.', 22, null, 'BHD', '["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'noor-co'), 4.7, 168, 0, true, false, true, '{"serum","hydration"}'),
  ('Overnight Retinol Renewal Cream', 'overnight-retinol-renewal-cream', 'Time-released encapsulated retinol works with peptides and squalane to resurface, soften lines and refine texture while you sleep — with less irritation than traditional retinol.', 'Encapsulated retinol cream that smooths and refines overnight.', 28, 34, 'BHD', '["https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'velvet-atelier'), 4.6, 132, 0, true, true, false, '{"cream","anti-aging","retinol"}'),
  ('Rose Dew Facial Toner', 'rose-dew-facial-toner', 'Steam-distilled Damask rose water balances and hydrates while gentle PHAs sweep away dullness. A refreshing mist-on step for calm, glowing skin.', 'Alcohol-free Damask rose toner that soothes and refreshes.', 12.5, null, 'BHD', '["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'maison-lys'), 4.5, 96, 0, true, false, false, '{"toner","rose"}'),
  ('Gentle Cream Cleanser', 'gentle-cream-cleanser', 'A silky cream-to-milk cleanser that melts away makeup and impurities without stripping the skin barrier. Leaves skin clean, calm and never tight.', 'Creamy non-stripping cleanser for soft, comfortable skin.', 10, null, 'BHD', '["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'noor-co'), 4.4, 78, 0, true, false, false, '{"cleanser"}'),
  ('Barrier Repair Moisturiser', 'barrier-repair-moisturiser', 'A rich yet fast-absorbing moisturiser with ceramides, niacinamide and shea to restore a compromised barrier, lock in moisture and reduce redness.', 'Ceramide + niacinamide cream that rebuilds a resilient barrier.', 19.5, null, 'BHD', '["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'skincare'), (select id from public.brands where slug = 'kosei'), 4.7, 143, 0, true, false, true, '{"moisturiser","ceramide"}'),
  ('Velvet Matte Lipstick — Rosewood', 'velvet-matte-lipstick-rosewood', 'Richly pigmented rosewood matte that glides on creamy and sets to a soft-focus velvet finish. Infused with jojoba oil so lips stay comfortable, never dry.', 'Full-coverage matte lipstick with a weightless, comfy feel.', 9.5, null, 'BHD', '["https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'velvet-atelier'), 4.6, 201, 0, true, true, false, '{"lipstick","matte"}'),
  ('Luminous Silk Foundation', 'luminous-silk-foundation', 'A breathable, buildable foundation that evens tone while letting skin look like skin. Hydrating hyaluronic complex keeps the finish fresh for up to 16 hours.', 'Medium-coverage foundation with a natural radiant finish.', 21, 25, 'BHD', '["https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'aurelie-paris'), 4.5, 176, 0, true, false, false, '{"foundation","complexion"}'),
  ('Sunset Eyeshadow Palette', 'sunset-eyeshadow-palette', 'Twelve highly blendable warm-toned shades — silky mattes and foil shimmers — in a curated palette that takes you from soft daytime looks to bold evening drama.', '12 warm mattes and shimmers for day-to-night eyes.', 18, null, 'BHD', '["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'dune-rose'), 4.8, 254, 0, true, true, true, '{"eyeshadow","palette"}'),
  ('Featherlight Setting Powder', 'featherlight-setting-powder', 'A translucent, finely milled powder that sets makeup, controls shine and softly blurs pores for an airbrushed finish that lasts all day.', 'Finely milled powder that blurs and sets without cakiness.', 14, null, 'BHD', '["https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'kosei'), 4.4, 88, 0, true, false, false, '{"powder","setting"}'),
  ('Lengthening Volume Mascara', 'lengthening-volume-mascara', 'A tapered brush and flexible formula wrap every lash for dramatic length and volume that holds its curl all day and removes easily with warm water.', 'Buildable mascara for length, lift and clump-free volume.', 11, null, 'BHD', '["https://images.unsplash.com/photo-1598662957563-ee4965d4d72c?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'noor-co'), 4.6, 190, 0, true, false, false, '{"mascara","eyes"}'),
  ('Dewy Glow Liquid Blush', 'dewy-glow-liquid-blush', 'A few dots melt into skin for a healthy, dewy flush of colour. Long-wearing and buildable, it works beautifully over makeup or bare skin.', 'Sheer liquid blush for a natural, lit-from-within flush.', 12.5, null, 'BHD', '["https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'makeup'), (select id from public.brands where slug = 'dune-rose'), 4.7, 121, 0, true, false, true, '{"blush","cheeks"}'),
  ('Oud Royale Eau de Parfum', 'oud-royale-eau-de-parfum', 'A regal unisex oud built on smoky agarwood, Damask rose and warm amber with a whisper of saffron. Long-lasting sillage crafted for the Gulf''s love of oud.', 'Opulent oud, rose and amber — a bold Arabian signature.', 52, 60, 'BHD', '["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'fragrance'), (select id from public.brands where slug = 'maison-lys'), 4.9, 312, 0, true, true, false, '{"perfume","oud","unisex"}'),
  ('Jasmine Nuit Eau de Parfum', 'jasmine-nuit-eau-de-parfum', 'An intoxicating floral built around night-blooming jasmine and tuberose, grounded by creamy sandalwood and vanilla for an elegant, romantic trail.', 'Night-blooming jasmine, tuberose and creamy sandalwood.', 45, null, 'BHD', '["https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'fragrance'), (select id from public.brands where slug = 'aurelie-paris'), 4.8, 205, 0, true, true, false, '{"perfume","floral"}'),
  ('Amber & Musk Eau de Toilette', 'amber-musk-eau-de-toilette', 'A cosy, versatile blend of golden amber, white musk and a hint of vanilla — clean and comforting, perfect for daily wear.', 'Soft, skin-like amber and musk for everyday elegance.', 34, null, 'BHD', '["https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'fragrance'), (select id from public.brands where slug = 'velvet-atelier'), 4.6, 140, 0, true, false, false, '{"perfume","amber","musk"}'),
  ('Citrus Bloom Body Mist', 'citrus-bloom-body-mist', 'A sparkling body mist of bergamot, peony and white tea for an instant refresh. Light enough to layer and reapply throughout the day.', 'Refreshing bergamot and peony mist for a light daily veil.', 16, null, 'BHD', '["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'fragrance'), (select id from public.brands where slug = 'dune-rose'), 4.4, 74, 0, true, false, true, '{"mist","fresh"}'),
  ('Argan Repair Hair Oil', 'argan-repair-hair-oil', 'A fast-absorbing blend of Moroccan argan and camellia oils tames frizz, seals split ends and leaves hair glossy — never greasy. Heat-protects to 220°C.', 'Weightless argan oil that smooths frizz and adds shine.', 17, null, 'BHD', '["https://images.unsplash.com/photo-1583209814683-c023dd293cc6?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1607602132700-068258431c6c?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'hair'), (select id from public.brands where slug = 'kosei'), 4.7, 158, 0, true, true, false, '{"hair-oil","repair"}'),
  ('Silk Bond Repair Shampoo', 'silk-bond-repair-shampoo', 'A sulphate-free shampoo with bond-building technology and silk proteins that gently cleanses while restoring strength to over-processed, brittle hair.', 'Bond-building shampoo that strengthens damaged hair.', 13.5, null, 'BHD', '["https://images.unsplash.com/photo-1607602132700-068258431c6c?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'hair'), (select id from public.brands where slug = 'noor-co'), 4.5, 92, 0, true, false, false, '{"shampoo"}'),
  ('Hydrating Hair Mask', 'hydrating-hair-mask', 'An intensive weekly treatment with shea butter and hydrolysed keratin that deeply nourishes dry, damaged lengths for softer, more manageable hair in one use.', 'Deep-conditioning weekly mask for soft, manageable hair.', 15, 18, 'BHD', '["https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'hair'), (select id from public.brands where slug = 'velvet-atelier'), 4.6, 110, 0, true, false, false, '{"mask","conditioning"}'),
  ('Neroli Body Lotion', 'neroli-body-lotion', 'A lightweight, fast-absorbing lotion scented with neroli and orange blossom, enriched with shea and glycerin for all-day, non-greasy hydration.', 'Fast-absorbing neroli lotion for 24h softness.', 11.5, null, 'BHD', '["https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'bath-body'), (select id from public.brands where slug = 'maison-lys'), 4.5, 83, 0, true, false, false, '{"lotion","body"}'),
  ('Exfoliating Sugar Scrub', 'exfoliating-sugar-scrub', 'A melting sugar scrub with cane crystals and nourishing oils that buffs away dullness and leaves skin polished, soft and lightly scented.', 'Cane-sugar scrub that polishes skin silky-smooth.', 9, null, 'BHD', '["https://images.unsplash.com/photo-1631214540553-ff044a3ff1d4?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'bath-body'), (select id from public.brands where slug = 'dune-rose'), 4.4, 67, 0, true, false, true, '{"scrub","exfoliate"}'),
  ('Shea Hand Cream Trio', 'shea-hand-cream-trio', 'A trio of richly nourishing shea hand creams in three signature scents. Beautifully boxed and travel-sized — an ideal gift or handbag essential.', 'Three travel hand creams — the perfect little gift.', 8.5, 10, 'BHD', '["https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'bath-body'), (select id from public.brands where slug = 'kosei'), 4.6, 129, 0, true, false, false, '{"hand-cream","gift"}'),
  ('Jade Facial Roller & Gua Sha Set', 'jade-facial-roller-gua-sha-set', 'A genuine jade roller and gua sha stone that cool and sculpt — massage to de-puff, boost circulation and help serums absorb. Comes in a keepsake pouch.', 'Cooling jade roller and gua sha for a de-puffing ritual.', 14.5, null, 'BHD', '["https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=1400&q=80","https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'tools'), (select id from public.brands where slug = 'velvet-atelier'), 4.7, 175, 0, true, true, false, '{"tools","gift","ritual"}'),
  ('Pro Blending Makeup Brush Set', 'pro-blending-makeup-brush-set', 'Ten ultra-soft vegan brushes for face and eyes, with a chic vegan-leather roll. Densely packed synthetic bristles blend product seamlessly for a pro finish.', '10-piece vegan brush set for a flawless application.', 22, 27, 'BHD', '["https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?auto=format&fit=crop&w=1400&q=80"]'::jsonb, (select id from public.categories where slug = 'tools'), (select id from public.brands where slug = 'aurelie-paris'), 4.5, 98, 0, true, false, true, '{"brushes","tools","vegan"}')
on conflict (slug) do update set
  name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, price = excluded.price,
  compare_at_price = excluded.compare_at_price, images = excluded.images,
  category_id = excluded.category_id, brand_id = excluded.brand_id,
  rating = excluded.rating, review_count = excluded.review_count,
  stock_quantity = excluded.stock_quantity, in_stock = excluded.in_stock,
  is_featured = excluded.is_featured, is_new = excluded.is_new, tags = excluded.tags;
